"""
tests/sample_series.py
=========================
Sample `series` documents shaped like the documents stored in MongoDB
(same keys, same nesting for network/web_channel/cast).

These are original, hand-written descriptions used only to exercise the
recommendation pipeline in environments where a live MongoDB connection
isn't available (e.g. this sandbox). Swap this out for
`mongo_manager.get_all_series()` against your real database — the
recommender code itself doesn't know or care where the documents came
from.
"""

from typing import Any, Dict, List

SAMPLE_SERIES: List[Dict[str, Any]] = [
    {
        "series_id": 1001,
        "name": "Ashfall City",
        "original_name": None,
        "language": "English",
        "genres": ["Crime", "Drama", "Thriller"],
        "status": "Ended",
        "premiered": "2015-01-12",
        "ended": "2019-11-03",
        "runtime": 55,
        "average_runtime": 55,
        "rating": 8.4,
        "weight": 90,
        "summary": "A burnt-out detective is pulled back into the criminal "
                    "underworld of a rain-soaked city to hunt the syndicate "
                    "that destroyed his family.",
        "network": {"id": 1, "name": "AMZ Network", "country": {"name": "United States"}},
        "web_channel": None,
        "official_site": None,
        "image_medium": "https://example.com/ashfall_city_medium.jpg",
        "image_original": "https://example.com/ashfall_city_original.jpg",
        "imdb_id": "tt1000001",
        "thetvdb_id": 200001,
        "updated": 1690000000,
        "cast": [
            {"person_id": 1, "person_name": "Daniel Ortiz", "character_name": "Det. Marcus Vale", "image_medium": None},
            {"person_id": 2, "person_name": "Priya Shah", "character_name": "Captain Reyes", "image_medium": None},
        ],
    },
    {
        "series_id": 1002,
        "name": "Harborline",
        "original_name": None,
        "language": "English",
        "genres": ["Crime", "Drama"],
        "status": "Ended",
        "premiered": "2017-03-05",
        "ended": "2021-06-14",
        "runtime": 50,
        "average_runtime": 50,
        "rating": 7.9,
        "weight": 80,
        "summary": "A dockside police unit investigates a smuggling ring "
                    "while a young detective struggles to prove herself to "
                    "a department that doesn't trust outsiders.",
        "network": {"id": 1, "name": "AMZ Network", "country": {"name": "United States"}},
        "web_channel": None,
        "official_site": None,
        "image_medium": "https://example.com/harborline_medium.jpg",
        "image_original": "https://example.com/harborline_original.jpg",
        "imdb_id": "tt1000002",
        "thetvdb_id": 200002,
        "updated": 1690000001,
        "cast": [
            {"person_id": 2, "person_name": "Priya Shah", "character_name": "Det. Elena Cho", "image_medium": None},
            {"person_id": 3, "person_name": "Tom Fielding", "character_name": "Sgt. Boone", "image_medium": None},
        ],
    },
    {
        "series_id": 1003,
        "name": "Lightless Frontier",
        "original_name": None,
        "language": "English",
        "genres": ["Science-Fiction", "Drama", "Adventure"],
        "status": "Running",
        "premiered": "2020-09-01",
        "ended": None,
        "runtime": 45,
        "average_runtime": 45,
        "rating": 8.7,
        "weight": 95,
        "summary": "The crew of a damaged colony ship must ration dwindling "
                    "power as they search for a habitable world at the edge "
                    "of known space.",
        "network": None,
        "web_channel": {"id": 10, "name": "Streamix", "country": None},
        "official_site": None,
        "image_medium": "https://example.com/lightless_frontier_medium.jpg",
        "image_original": "https://example.com/lightless_frontier_original.jpg",
        "imdb_id": "tt1000003",
        "thetvdb_id": 200003,
        "updated": 1690000002,
        "cast": [
            {"person_id": 4, "person_name": "Aiko Tanaka", "character_name": "Cmdr. Iris Wren", "image_medium": None},
            {"person_id": 5, "person_name": "Marcus Boyd", "character_name": "Eng. Sol Ade", "image_medium": None},
        ],
    },
    {
        "series_id": 1004,
        "name": "Second Horizon",
        "original_name": None,
        "language": "English",
        "genres": ["Science-Fiction", "Drama"],
        "status": "Running",
        "premiered": "2022-02-18",
        "ended": None,
        "runtime": 42,
        "average_runtime": 42,
        "rating": 8.1,
        "weight": 88,
        "summary": "A generation ship's engineers race to repair a failing "
                    "reactor before the last habitable deck runs out of "
                    "power, forcing hard choices about who gets to survive.",
        "network": None,
        "web_channel": {"id": 10, "name": "Streamix", "country": None},
        "official_site": None,
        "image_medium": "https://example.com/second_horizon_medium.jpg",
        "image_original": "https://example.com/second_horizon_original.jpg",
        "imdb_id": "tt1000004",
        "thetvdb_id": 200004,
        "updated": 1690000003,
        "cast": [
            {"person_id": 5, "person_name": "Marcus Boyd", "character_name": "Chief Eng. Otto Reyes", "image_medium": None},
            {"person_id": 6, "person_name": "Nadia Kessler", "character_name": "Dr. Wren Sato", "image_medium": None},
        ],
    },
    {
        "series_id": 1005,
        "name": "The Bakeshop on Third",
        "original_name": None,
        "language": "English",
        "genres": ["Comedy", "Romance"],
        "status": "Ended",
        "premiered": "2016-05-20",
        "ended": "2018-08-11",
        "runtime": 30,
        "average_runtime": 30,
        "rating": 7.2,
        "weight": 60,
        "summary": "A small-town baker reluctantly partners with a big-city "
                    "chef to save her family's failing bakery, and neither "
                    "of them expected to fall for the other along the way.",
        "network": {"id": 2, "name": "Sunview Broadcasting", "country": {"name": "United States"}},
        "web_channel": None,
        "official_site": None,
        "image_medium": "https://example.com/bakeshop_medium.jpg",
        "image_original": "https://example.com/bakeshop_original.jpg",
        "imdb_id": "tt1000005",
        "thetvdb_id": 200005,
        "updated": 1690000004,
        "cast": [
            {"person_id": 7, "person_name": "Grace Lin", "character_name": "Maddie Ross", "image_medium": None},
            {"person_id": 8, "person_name": "Ben Whitfield", "character_name": "Chef Leo Marsh", "image_medium": None},
        ],
    },
    {
        "series_id": 1006,
        "name": "No Vacancy",
        "original_name": None,
        "language": "English",
        "genres": ["Comedy"],
        "status": "Running",
        "premiered": "2023-01-09",
        "ended": None,
        "runtime": 25,
        "average_runtime": 25,
        "rating": 7.5,
        "weight": 55,
        "summary": "The mismatched staff of a rundown seaside motel try to "
                    "keep the doors open through one chaotic guest disaster "
                    "after another.",
        "network": {"id": 2, "name": "Sunview Broadcasting", "country": {"name": "United States"}},
        "web_channel": None,
        "official_site": None,
        "image_medium": "https://example.com/no_vacancy_medium.jpg",
        "image_original": "https://example.com/no_vacancy_original.jpg",
        "imdb_id": "tt1000006",
        "thetvdb_id": 200006,
        "updated": 1690000005,
        "cast": [
            {"person_id": 9, "person_name": "Owen Park", "character_name": "Ray Delgado", "image_medium": None},
        ],
    },
    {
        "series_id": 1007,
        "name": "Quiet Hollow",
        "original_name": None,
        "language": "English",
        "genres": ["Horror", "Mystery"],
        "status": "Ended",
        "premiered": "2014-10-01",
        "ended": "2015-12-20",
        "runtime": 45,
        "average_runtime": 45,
        "rating": 6.9,
        "weight": 40,
        "summary": "Strange disappearances plague a fog-bound Appalachian "
                    "town, and the new sheriff starts to suspect the woods "
                    "themselves are hunting the residents.",
        "network": None,
        "web_channel": None,
        "official_site": None,
        "image_medium": None,
        "image_original": None,
        "imdb_id": "tt1000007",
        "thetvdb_id": 200007,
        "updated": 1690000006,
        "cast": None,
    },
    # Deliberately sparse / missing-data documents, to exercise the
    # "missing data does not crash the system" requirement.
    {
        "series_id": 1008,
        "name": "Untitled Pilot",
        "original_name": None,
        "language": None,
        "genres": [],
        "status": "In Development",
        "premiered": None,
        "ended": None,
        "runtime": None,
        "average_runtime": None,
        "rating": None,
        "weight": None,
        "summary": None,
        "network": None,
        "web_channel": None,
        "official_site": None,
        "image_medium": None,
        "image_original": None,
        "imdb_id": None,
        "thetvdb_id": None,
        "updated": None,
        "cast": None,
    },
    {
        # No usable text content at all: must be skipped during build,
        # not crash it.
        "series_id": 1009,
        "name": "Blank Slate",
        "original_name": None,
        "language": None,
        "genres": [],
        "status": None,
        "premiered": None,
        "ended": None,
        "runtime": None,
        "average_runtime": None,
        "rating": None,
        "weight": None,
        "summary": None,
        "network": None,
        "web_channel": None,
        "official_site": None,
        "image_medium": None,
        "image_original": None,
        "imdb_id": None,
        "thetvdb_id": None,
        "updated": None,
        "cast": None,
    },
]
